### PR TITLE
remove react-native peer dependency

### PR DESCRIPTION
**Pull request by chirag04**

### CODE REVIEW

**Comment by taion** [comment]
Worth replacing this with a peer dep on React proper?

**Comment by taion** [comment]
Would need to replace https://github.com/martyjs/marty-native/blob/v0.10.4/marty.js#L17-L23 as well, I think.

**Comment by chirag04** [comment]
react-native now peer depend on react already.

**Comment by taion** [comment]
wdyt of #4?

**Comment by taion** [comment]
Superseded by #4.

**Pull request closed without merging**
